### ISSUE TITLE
Question: what is the naming rule for character PNG images?

### ISSUE THREAD

**Issue by qqhann** [soarteam/Arknights#11]
Thanks for maintaining this repo.
I'm interested in using character portrait images. Such as:
<img width="300px" src="https://raw.githubusercontent.com/soarteam/Arknights/master/siege%E6%8E%A8%E8%BF%9B%E4%B9%8B%E7%8E%8B/char_112_siege_1.png" />

I wonder what is the naming rule and what is the number.
For example, `char_112_siege_1.png` seems to follow some rule. Separating it with `_`:
- `char` just indicates this is a character image.
- `112` sounds like a unique number for the character. But I wonder where does it come from? From the game source data, or do you count every operator and number them? What makes me wonder is the number seems very random. 
- `siege` should be the character's English name.
- `1` This is another mystery to me. `1` sounds like default skin. `2` looks like promoted skin. But some characters don't follow this rule. They do not have `1` or `2` but have `1[alpha]_` or `2[alpha]_`. I wonder where do they come from. And can we normalize it so that it is easier to use them programmatically?

**Comment by soarteam** [comment]
Thanks for your interest.
In fact, this rule is from Hypergryph. You could see it in Arknights's Char Assets package.
I think there's some rule similar to what you mentioned. But many times it does not follow certain rules.
"112" is the serial number of characters.
"siege" is Skin's name, NOT the character's English name.
Most of the time, I recommend you use a wildcard such as "*" to match the PNG files.
And I always discard *b* file, because they are low-resolution images.

**Comment by soarteam** [comment]
For default skin, may it's the character's English name. But for additional skin, it's skin's name.
And I recommend you always check the PNG resolution. 
You could see, sometimes, 1[alpha]_ and 2[alpha]_ are masks of different resolutions.

**Comment by qqhann** [comment]
@soarteam Thanks for your answer!

> In fact, this rule is from Hypergryph. You could see it in Arknights's Char Assets package.

Do you mean you are gathering these assets from the game itself?
How do you do that?
Are you extracting files from the Android build (for example using methods from [this page](https://www.bilibili.com/read/cv2777112/))?
If you have a good workflow or reference, could you tell me that?

**Comment by qqhann** [comment]
BTW, according to [this post](https://tieba.baidu.com/p/6867238650), `[alpha]` sounds like ignoreable?

**Comment by soarteam** [comment]
https://www.bilibili.com/video/BV1V741157nC/
https://www.bilibili.com/video/BV1g7411n79y/
https://www.bilibili.com/video/BV137411F76f/
https://www.bilibili.com/video/BV1AA411872L/
https://www.bilibili.com/video/BV1n7411C7u1/
